version: '3'

services:

  pet-collector-mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27020:27017"
    container_name: pet-collector-mongo
    hostname: mongodb
    volumes:
      - ./dockervolume/mongo/mongodb:/data/db
      - ./dockervolume/mongo/mongoconfigdb:/data/configdb
      - ./init_db.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      - MONGO_INITDB_DATABASE = api_prod_db

  pet-collector-server:
    image: petcollector-server:latest
    ports:
      - "8085:8085"
    container_name: pet-collector-server
    hostname: pc-server
    depends_on:
      - pet-collector-mongo
      - rabbitmq
    environment:
    #mongodb
      - spring.data.mongodb.host=mongodb
      - spring.data.mongodb.port=27017
      - spring.data.mongodb.database=pet_collector
    #rabbitmq
      - rabbitmq.host=rabbitmq
      - rabbitmq.port=5672

  pet-collector-authenticator:
    image: petcollector-authenticator:latest
    ports:
      - "8090:8090"
    container_name: pet-collector-authenticator
    hostname: pc-auth
    depends_on:
      - pet-collector-mongo
    environment:
    #mongodb
      - spring.data.mongodb.host=mongodb
      - spring.data.mongodb.port=27017
      - spring.data.mongodb.database=pet_collector
    #rabbitmq
      - rabbitmq.host=rabbitmq
      - rabbitmq.port=5672

  krakend:
    image: devopsfaith/krakend:latest
    ports:
      - "8080:8080"
    container_name: krakend-gateway
    depends_on:
      - pet-collector-authenticator
      - pet-collector-server

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro