@protocol = http
@hostname = localhost
@port = 8085
@host = {{protocol}}://{{hostname}}:{{port}}

### return list of debts
GET {{host}}/api/debt

### return debt with id
GET {{host}}/api/debt?userId=643715296f76850a69071023

### create new debt
POST {{host}}/api/debt?userId=643715296f76850a69071023
Content-Type: application/json

{
    "totalSum":234,
    "comment":"dfdsfsfdsf",
    "version":0,
    "debtors":[
        {
            "userId":"643715296f76850a69071023",
            "sum":234
        }
    ]
}

### update debt

PUT {{host}}/api/debt
Content-Type: application/json

{
    "id": "63b859bf9d18c300961bd24b",
    "ownerId": "63b859569d18c300961bd247",
    "debtorId": "63b859589d18c300961bd248",
    "sum": 320.0
}

### delete debt with id

DELETE  {{host}}/api/debt/63b859bf9d18c300961bd24b