version: '3'

services:

  pet-collector-mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    container_name: pet-collector-mongo
    hostname: mongodb
    volumes:
      - /volumes/mongodb:/data/db
      - /volumes/mongoconfigdb:/data/configdb

  pet-collector-server:
    image: petcollector:latest
    ports:
      - "8080:8080"
    container_name: pet-collector-server
    depends_on:
      - pet-collector-mongo
