### return list of users
GET http://localhost:8080/api/user

### return user with id
GET http://localhost:8080/api/user/123

### create new user
POST http://localhost:8080/api/user
Content-Type: application/json

{
    "lastName": "Derevyankin",
    "firsName": "Denis",
    "midleName": "Sergeevich",
    "login": "derevyankindenis",
    "password": "424242",
}



